# fly.toml app configuration file generated for infinimed-launch-1 on 2025-01-12T16:07:47+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shongi-server'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
